name: prettier

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]  

jobs:
  prettier:
    container: 
 #   runs-on: ubuntu-latest
      image: node:14.17.0-alpine
    steps: 
    - uses: actions/checkout@v2
    - name: prettier source code with eslint
      run: npm run prettier           